### ISSUE TITLE
List Release number at bottom of Data.EnviroDIY.org page

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#116]
Possibly at the bottom of the "Developed by" column?

Include link to corresponding GitHub release notes, such as https://github.com/ODM2/ODM2WebSDL/releases/tag/0.4.0.

Note that I modified the Release Notes to add notes linking to the corresponding Milestone, because since completing #63, Release numbers are linked to Milestone numbers.

**Comment by horsburgh** [comment]
@Maurier - I'm adding this one to Release 0.7 which is all of the front end stuff to restyle the site.

**Comment by horsburgh** [comment]
I see this on the bottom of the page. It needs to point at the right release number - this one will be 0.7.0, not 0.6.0. I would like it to include a label and be formatted as follows:

Release: Version 0.7.0

The "Version 0.7.0" text should be linked to the GitHub release page for 0.7.0.

I'm adding the "ready for testing" label because it's on the sandbox, but these changes need to be made before we can call this one tested.

**Comment by horsburgh** [comment]
Done on sandbox. Adding tested label.
