### ISSUE TITLE
Last measurement times are wrong (again....)  Time zone problem

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#234]
![image](https://user-images.githubusercontent.com/5374350/39331701-3fea88b0-4973-11e8-92eb-4df13ef0681b.png)

This sensor's data is actually only 13 minutes old, not 5 hours and 13 minutes old.  The sensor is posting in UTC-5 and the last point was 3:45pm, which would be 4:45 in UTC-4.  My pc clock is in UTC-4.

**Comment by SRGDamia1** [comment]
The time last updated is correct on the status page, it is only incorrect in the MySites page.

**Comment by aufdenkampe** [comment]
I noticed this issue too, but if I remember, the issue was with daylight saving time.

In other words, the website is comparing my laptop time, in daylight savings time, to the data logger real time clock timestamp, which is in standard time, and saying, for example, that it's been 1 hour and 2 minutes since the last reading when it's only been 2 minutes.

**Comment by horsburgh** [comment]
@jcaraballo17 - given that this is a bug, it needs to get fixed. Have you addressed this yet? If not, can you give us a status update on what needs to be done to address this? We need to decide if this should stay in the 0.8 milestone for release. I don't want it to hold up rolling out the leaf pack network functionality.

**Comment by horsburgh** [comment]
I added some data to a site on the sandbox, and the date of the last observation is listed correctly. I'm going add the Tested label to this one.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
