### ISSUE TITLE
Highlight QC status in spark lines

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#260]
Add a warning noting that the data is very raw.

**Comment by SRGDamia1** [comment]
This only needs to be a visual flag at the top of the spark-line.

![image](https://user-images.githubusercontent.com/5374350/40923821-cc0893bc-67e3-11e8-8112-848d5d1cd7d4.png)

I'm not sure if there should be a warning on each spark-line or a single one at the top below the 72 hour warning.  Right now there is now way to upload data at any QA/QC level other than 0/Raw, but if there were to be a way in the future to add higher QA/QC level data, then we'd want the warning to be tied to the spark-line

**Comment by SRGDamia1** [comment]
Similar to warnings issued by USGS:

![image](https://user-images.githubusercontent.com/5374350/40924075-6423464c-67e4-11e8-819f-748a6be0c5c8.png)

**Comment by SRGDamia1** [comment]
Is this simple enough to add to the priority time series features milestone?

**Comment by Maurier** [comment]
This is simple enough to add right now. Just let me know what your decision is regarding where to put it.

**Comment by horsburgh** [comment]
Given that all of the data are raw, we should have one statement above the sparklines that states this. The data aren't really provisional, because that means that they could change in the future. We have no mechanism for changing data. I suggest the following statement/warning to be added to the existing message at the top of the spark lines:

"Only the most recent 72 hours of available data are shown on the sparkline plots. The plots are broken when there are gaps in the data longer than 6 hours. Plots shaded in green have recent data. Plots shaded in red have not reported data in the last 72 hours. All data shown are raw observations and have not been subject to quality control post processing."

**Comment by SRGDamia1** [comment]
Actually, the consensus (reached just this moment) at Stroud is to put it per time-series in case the functionality to display non-raw data is ever available.

Is there an ODM2 vocabulary for the observation quality control level (0-5)?  If so, can the flag possibly link to a description of that vocabulary term?

**Comment by horsburgh** [comment]
There is no QCLevel vocabulary. This seems really redundant.

**Comment by SRGDamia1** [comment]
No link is fine, too...

**Comment by horsburgh** [comment]
@Maurier showed me yesterday that he had added the label to the sparkline plots with the text I wrote above as hover text when you hover over that label.

> All data shown are raw observations and have not been subject to quality control post processing.

**Comment by SRGDamia1** [comment]
Great!

**Comment by horsburgh** [comment]
@Maurier - I just tested this on the sandbox. It is working correctly, but for some reason the "Provisional" label is wrapping below the variable name text in some cases.

![image](https://user-images.githubusercontent.com/3485902/41184494-dde4d1c4-6b3d-11e8-823a-5e65e2556eef.png)

Looks good otherwise.

**Comment by horsburgh** [comment]
I tried this again for my site and I'm only noticing it now at very narrow window sizes. I think this is reasonable and so I'm adding the Tested label to this one.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
