### ISSUE TITLE
export zip...compiling files not working 

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#296]
You can only click five variables (which may be intentional but possibly should be noted) and then when you click the export tab it just goes to "compiling files..." indefinitely and doesn't produce a zip file

![image](https://user-images.githubusercontent.com/39309124/46041571-16f30500-c0e1-11e8-91ea-ab8d4d0e71ea.png)

**Comment by jcaraballo17** [comment]
@Maurier can you take a look at this?

**Comment by Maurier** [comment]
@jcaraballo17 Yeah, I have already identified the problem. Will push a fix soon.

**Comment by horsburgh** [comment]
@Maurier - I just had a look at this. The "Export Selected (.zip)" button created a zip file and it downloaded fine. Inside were CSV files for the time series I selected. The header information was there, but there were no datavalues in the files.

**Comment by Maurier** [comment]
@horsburgh, this is part of another problem specific to this deployment that @jcaraballo17 and I discovered last night. In short, the site has a problem accessing the datapoints for any dataset.  @jcaraballo17 any ideas how to fix it?

**Comment by Maurier** [comment]
@horsburgh This issue can be tested now.

**Comment by horsburgh** [comment]
I just tested this. The zip file is now being created, and the CSV files are being zipped correctly and the download works. For the purposes of this issue, I'm going to add the "tested" label because the reported issue has been resolved. However, when I look at the CSV files, there's some issues with the header information and the date/time values. I'm going to make this a separate issue.

**Comment by aufdenkampe** [comment]
Worked for me! Thanks.
