### ISSUE TITLE
No data emails not being sent

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#299]
The SWRCWetLab site should be notifying me after no data received for > 6 hours.  It's gone down several times recently and I have not received any emails.

**Comment by aufdenkampe** [comment]
This feature has not been working for me either. Thanks for creating this issue!

**Comment by horsburgh** [comment]
@jcaraballo17 - how can I test this?

**Comment by jcaraballo17** [comment]
[Go to any site page with data, then go to it's Edit site page.](http://envirodiysandbox.usu.edu/sites/update/WSU-3/)
At the bottom of the form check the "Notify me if site stops receiving sensor data." and fill that out.
The script that regularly checks the data runs every 15 minutes, so in < 15 mins it'll send you an email.

**Comment by horsburgh** [comment]
I set this up on one of my sites that had old data with nothing recent. Within 15 minutes I received an alert message:

Jeff,

This email is to notify you that your EnviroDIY site "Little Bear River at Mendon Road near Mendon, UT" has not received any new data values in the last 88425 hours. The last update was on 2008-10-01 05:30:00. You may want to check your equipment to ensure it's working as intended.

https://data.envirodiy.org/sites/USU-LBR-Mendon/

Best regards,
The EnviroDIY team.

@jcaraballo17 - can you update the text of this email message as follows:
1. Change "This email is to notify you that your EnviroDIY site..." to "This email is to notify you that your Monitor My Watershed site..."
2. Change the text to use the right domain in the URL (instead of data.envirodiy.org use monitormywatershed.org). 
3. Change "The EnviroDIY" team to "The Monitor My Watershed Team" with no period.

As soon as you fix these, add the tested label to this one.

**Comment by aufdenkampe** [comment]
That's great to see it working!
Thanks @horsburgh for suggesting those text changes.
