### ISSUE TITLE
Password reset attempt yields 504 gateway time-out error

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#373]
I attempted to reset my password as part of testing before publicizing the portal to Leaf Pack Network users. The process spins for a while and then times out. This had also been reported to me by an EnviroDIY user.

**Comment by aufdenkampe** [comment]
Thanks for finding this bug!

As with #372, @steveskrip and I will look into it and ping @jcaraballo17 for a quick suggestion.

**Comment by aufdenkampe** [comment]
This is likely due to the fact that the code still leverages USU's email system. Working on confirming this and finding an alternative email system.

**Comment by jcaraballo17** [comment]
Fixed in https://github.com/ODM2/ODM2DataSharingPortal/pull/395.
- Created a Gmail account to use for sending the password recovery and site alert emails.
- Added the email username and password to the settings file.
- Setup the email django system to use the credentials mentioned above to send via Gmail's smtp system.

**Comment by jcaraballo17** [comment]
Tested it by successfully using the password recovery and setting up a site alert.

**Comment by aufdenkampe** [comment]
Yes, my Site Alerts are now working!

**Comment by aufdenkampe** [comment]
I just tried a password reset, and I got it to work!
