### ISSUE TITLE
How to Install in more Detail

### ISSUE THREAD

**Issue by kieutuandung-tlu** [ODM2/ODM2DataSharingPortal#376]
I am beginner with Django, so when I followed your guide, i can't continue at Steps 6.
[https://github.com/ODM2/ODM2DataSharingPortal/blob/master/doc/deployment_guide.md](url)
ODM2DataSharingPortal structure was cloned quite different with normal Django Project's structure in my understand.
Could you please show me how to install in more details (video is the best if you could).
Hope to receive your suppport

**Comment by johnandrea** [comment]
I have the same problem: stopped at step 6.

a) Requirement for postgis is missing

b) Does the copy command mean copy to "." or in same path as the template. In any case the .json file is not found by manage.py. Should the virtualenv copy of settings.py be modified to handle json files.

c) Assuming past b) is it ok to run 'manage.py migrate' in order to build the django tables

d) Is it ok to run manage.py createsuperuser

e) Shouldn't static_root default to os.path.join(PROJECT_ROOT, '../../dataloaderinterface/static/dataloaderinterface/')

f) Missing install notes for influx db. Can it be skipped by removing lines in settings file.

g) Missing install notes for tsa catalog. Can it be skipped by removing lines in settings file.

h) Missing install notes for hydroshare. Can it be skipped by removing lines in settings file.

i) What is Google API used for ? If used for maps, can mapbox/leaflet be used instead.

j) Is crontab_log_file setting a full path or a filename

k) Is crontab_user setting the owner of the files

l) Is email_host setting an SMTP relay which could be localhost

Thanks

**Comment by aufdenkampe** [comment]
In the last year since we've been actively maintaining this repo, we've substantially updated things since then, including the deployment guide.
