### ISSUE TITLE
Wikiwatershed -Monitor my watershed download data issue

### ISSUE THREAD

**Issue by Streambug** [ODM2/ODM2DataSharingPortal#396]
When downloading data: http://monitormywatershed.org/sites/WCD696/ 
and clicking to the time series analyst window: http://www.monitormywatershed.org/tsa/?sitecode=WCD696&variablecode=Decagon_CTD-10_Temp&view=visualization&plot=true

Then to export data from 3/22/2019 to 5/30/19  under dataset tab.  The export tab switches to "compiling data" but never downloads anything. 

I was able to eventually get the data another pathway but wanted to share because for myself that was the most intuit pathway to get data for the specified dates and it didn't work. 

Thanks

**Comment by HeatherBrooks** [comment]
@aufdenkampe, I had another report of this through the WikiWatershed contact form on 27 June 2019: "In Time Series Analyst I choose variables to graph and they graph fine, but when i try to export files it just spins and never completes." Is this being looked at?

Thanks @streambug for reporting. Can you share here the other pathway you used to download the data so I can post it on the Monitor My Watershed help page?

**Comment by aufdenkampe** [comment]
Thanks @HeatherBrooks. We've had a good number of TSA issues this month on production, which we've hot-fixed, so it could be related to those.

Also, I'm thinking that this will be fixed with the fix for #329, which is now ready for testing at https://staging.monitormywatershed.org.

**Comment by HeatherBrooks** [comment]
I just tried downloading two months worth of data for the same site and sensor (WCD696, CTD-10) on the staging site, and it is still stuck at "Compiling files." But I'm not super familiar with sensor data and the TSA, so maybe someone else should test.

**Comment by HeatherBrooks** [comment]
I tested this on staging and it still hangs up on "Compiling files" when I try to download two months of data for site WCD696.

**Comment by aufdenkampe** [comment]
Thanks @HeatherBrooks for all your testing. We'll look at this.

**Comment by jcaraballo17** [comment]
Both the TSA file compilation issue and the Data Portal download error were fixed back in January, but those fixes never made their way to production. I've updated the staging server's TSA with that fix, and it should be working now.

Just tried downloading one and a few series from the same site mentioned above and it works. 
https://staging.monitormywatershed.org/tsa/?sitecode=WCD696&variablecode=Decagon_CTD-10_Temp&view=datasets

Could also download both individual and multiple series csv files generated by the data portal. Although there's no indication that you have to wait or if it's working or not. This should be it's own separate issue.
https://staging.monitormywatershed.org/sites/WCD696/

**Comment by aufdenkampe** [comment]
@HeatherBrooks & @jcaraballo17,

From my testing, data download works just fine from https://staging.monitormywatershed.org/sites/WCD696/

However, when I go here
http://staging.monitormywatershed.org/tsa/?sitecode=WCD696&view=datasets&plot=false
Then select 5 time series, then click on "Export selected (.zip)", that seems to "hang". 
Or maybe it just takes a very long time, because that site has so much data.

I got it to work when I just selected 1, 2, 3 or 4 variables, but it seemed to hang with 5 for some reason.

I got it to work for this site for 1 to 5 variables:
http://staging.monitormywatershed.org/tsa/?sitecode=160065_Limno_Crossroads&view=datasets&plot=false

So it seems like this issue is mostly fixed, except for a fringe case. I'm going to close it, as we hope to eventually refactor our CSV handling.
