### ISSUE TITLE
email using monitormywatershed.org

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#426]
I had an email today that referenced https://www.monitormywatershed.org/sites/LCC45a2/
which on clicking responded

"Bad Request (400)"

On using https://data.envirodiy.org/sites/LCC45a2/ 
it works OK.

I have never accessed monitormywatershed.org.     
I would think it either shouldn't be referencing monitormywatershed, or it should be being processed. (https://github.com/ODM2/ODM2DataSharingPortal/issues/316)

The details in the email "4906 hours" aren't accurate as the last update is "Aug. 7, 2019, 4:45 p.m. (UTC-08:00)"

I also recieved as similar email for https://www.monitormywatershed.org/sites/LCC45a3/ that is in use.

I did not receive emails for other sites that have not been in use in the last month.

Subject: | Monitor My Watershed Notification: No data received for site Laguna da Santa Rosa @ E.Cotati Ave, Cotati in the last 4906 hours
-- | --     
Thu, 08 Aug 2019 21:30:16 -0000      
EnviroDIY Site Alert <limnotech.monitormywatershed@gmail.com>     
neilh20+ww1809@wllw.net     

Neil,

This email is to notify you that your Monitor My Watershed site "Laguna da Santa Rosa @ E.Cotati Ave, Cotati" has not received any new data values in the last 4906 hours. The last update was on 2019-01-16 09:32:00. You may want to check your equipment to ensure it's working as intended.
https://www.monitormywatershed.org/sites/LCC45a2/    

Best regards,    
The Monitor My Watershed Team

**Comment by HeatherBrooks** [comment]
@neilh10 Sorry, I just saw this. Moving forward, we will be referring to the data portal as Monitor My Watershed because it is no longer solely focused on EnviroDIY data. I think you may have received these emails while we were in the process of pointing data.envirodiy.org to monitormywatershed.org; I see that the URLs in your issue are resolving properly now. If you're no longer having this problem I will close this issue. Thanks!

**Comment by neilh10** [comment]
Great. Fine by me closing.
