### ISSUE TITLE
WOFpy returning only most recent value

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#432]
Although @emiliom did a major fix, overhaul and update of our Water One Flow / WaterML web services with Python (WOFpy) deployment with the #379 fix and the last release of the MonitorMyWatershed.org portal, there has been one known remaining issue. 

Presently, all Get Values requests only return the most recent data value for the requested time period. 

For example the following should return all values, but only returns one.
https://monitormywatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy:CWS-ThomasDairy1&variable=envirodiy:Meter_Teros11_Temp

This example should return all values from the given 4-day period:
https://monitormywatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy:CWS-ThomasDairy1&variable=envirodiy:Meter_Teros11_Temp&startDate=2019-09-02T16:00:00&endDate=2019-09-06T16:10:00

**Comment by SRGDamia1** [comment]
Is there a known fix?

**Comment by emiliom** [comment]
> Is there a known fix?

Not yet. It's waiting for me to have the time to look into it.

**Comment by SRGDamia1** [comment]
Has anything changed with this?

**Comment by emiliom** [comment]
No, unfortunately. It's been hard to find the time for this. But I keep putting it on my calendar every week ... Maybe early next week. Fingers crossed.

**Comment by emiliom** [comment]
Adding a note based on initial exploration of this issue.

I'm pretty sure the source of this problem is found in `odm2_timeseries_dao.py`, within the `Odm2Dao.get_variables_from_results` method. Changes introduced in the [EnviroDIY deployment version of this DAO file](https://github.com/LimnoTech/ODM2DataSharingPortalConfig/blob/master/wofpy/var-www-wofpy/odm2_timeseries_dao.py#L151) introduced this bug, not present in the [earlier (I think) version found in the WOFpy repo](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L148).

**Comment by aufdenkampe** [comment]
@emiliom fixed this issue yesterday!
it's now available for testing at https://staging.monitormywatershed.org/wofpy/
