### ISSUE TITLE
Data isn't appearing in sparklines or TSA - but only for some parameters

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#436]
At this site:  http://data.envirodiy.org/sites/PKPC3S/

Data is being sent from the logger every 5 minutes.  The single most recent point seems to be correctly shown under the sparkline, but the sparklines themselves are empty for all variables except modem signal strength and RSSI.  TSA also shows only those two variables at that site.  But calling WoFPy or downloaded the csv from the site information page gives data for all paramaters

**Comment by aufdenkampe** [comment]
This is an issue with the connection to the InfluxDB database mirror getting hung up and not syncing for some or all time series. The InfluxDB mirror feeds Sparklines and TSA.

This issue has re-occurred repeatedly since starting to use InfluxDB (see #390, #378, #193, #131, #130, #99, etc.). The short term fix is to manually restart those connections. We have notes on how to do that, depending on what exactly is hanging up.

The long-term fix is to **Remove InfluxDB by using materialized views in PostgreSQL #434**.

**Comment by aufdenkampe** [comment]
Pasting from an email from @s-hicks2:

> Things have been going well at almost all of [our new stations], but we've had a few that aren't graphing their sparkline plots, and no data is viewable in TSA, except for radio signal strength/percent, which are 2 variables I added just a few days ago.  The text next to each blank sparkline plot updates every 5 minutes with the latest data, and if you choose the "Download Sensor Data" button, you can see that all of the data for all the parameters is there in the file.
> 
> These 5 sites were all created months ago, but never had any data sent to them because they had no telemetry until yesterday (or last week in the case of the bottom two). 
> 
> - http://monitormywatershed.org/sites/ROCK_DS2/  
> - http://monitormywatershed.org/sites/BENNETTSRUN4/ 
> - http://monitormywatershed.org/sites/BENNETTSRUN3/ 
> - http://monitormywatershed.org/sites/PKBH7S/ 
> - http://monitormywatershed.org/sites/PKPC3S/

**Comment by SRGDamia1** [comment]
All of those sites look okay now. I don't understand why they went off in the first place, but the full rebuild seems to have got it back up.

**Comment by aufdenkampe** [comment]
That is great news! Thank you for running the scripts and checking if it worked.

I don't know why parts of this always break over time either, but it is very frustrating. I'm really glad that we now know how to fix it ourselves. Those scripts that you ran were written from scratch by Juan in late January, because the other ones failed repeatedly during rebuild.

**Comment by dbressler75** [comment]
http://monitormywatershed.org/sites/SHPK5S/

It seems that data are not showing up in panels and cannot be visualized in TSA (it just spins), but the most recent observation is still showing at bottom of each panel and the main "download sensor data" tab does work.

**Comment by aufdenkampe** [comment]
@tslawecki just fixed it. Hopefully it won't break again.
