### ISSUE TITLE
TimeSeries with Multiple variables or  Singleton Unique Sensors

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#450]
I'm just wondering, having worked through 
https://github.com/ODM2/ODM2DataSharingPortal/issues/443
https://github.com/ODM2/ODM2DataSharingPortal/issues/444
that there are some architectural issues across a number of domains. 

Does anybody have the insight (or guesses)  to  know what is likely to work for a unique logger is
1) To have single unique sensors, that is a sensor can't be duplicated in a logger. It could be relatively easy to define unique miscellaneous sensor to cover duplicates of other sensors eg misc1..16
That is a unique variable code would always be reported in the TimeSeries. The downside of course is the quality of information has to be referenced to the sensors its duplicating.

2a) Can the TSA and other access packages like WOFpy be extended to handle unique instances of the same sensor type ie multiple time-series with the same variable code
2b)  Is that likely and what would the path be for that to happen.

So just curious to see if there are any views as to what direction the solution might go in.

**Comment by aufdenkampe** [comment]
Hi @neilh10, thanks for posting this issue. I've long been interested in fixing these fundamental constraints. Here's a bit of background on it all.

As @SRGDamia1 explained in https://github.com/ODM2/ODM2DataSharingPortal/issues/444#issuecomment-553458981, the TSA and WaterOneFlow (WOF) web services aren't capable of distinguishing anything other than the variable code, so the same sensor deployed from the same station but at two different depths both show up identically. This isn't an architectural issue of the ODM2DataSharingPortal, but rather a fundamental constraint of the data models (ODM1.1 and WaterML1.1) that was used to develop TSA and WOF (including the WOFpy library). We can't change ODM1.1 and WaterML1.1 because they are in widespread use elsewhere. 

We can however, eventually implement a WaterML2 web service and replace TSA with another plotting package that natively uses ODM2 (or significantly update TSA to TSA2?).  BTW, ODM2 was explicitly developed to overcome these and many other constraints with ODM1.1 and it's derivatives.

We hope to start addressing these issues with future releases. See our [Release 0.12 - Tech Debt / Refactor Code](https://github.com/ODM2/ODM2DataSharingPortal/milestone/14) milestone. However, we don't have funding for any development right now, so it won't be coming soon.

**Comment by neilh10** [comment]
Hi @aufdenkampe  thanks for the explanation. Appreciate the good work going on and building on previous layers and incremental approach. I really appreciate that it takes specific project goals and skills to go to the next revision. Thanks for putting together Release 0.12.

So working with the current data model WaterML1.1  if there is a need for unique access from WOF, then it needs to be a unique variable code for the individual sensors readings.  I have been prototyping it, and there are lot of unique variables to play with.
