### ISSUE TITLE
merge Browse Sites and Time Series Analyst tabs?

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#463]
For clarity it might be beneficial to merge the Browse Sites and TSA tabs (in upper left of main MonitorMW page) into one main tab for accessing and graphing data.  Currently the two tabs seem to function slightly different from one another but do not provide dramatically different functions so it just confuses the process.

**Comment by SRGDamia1** [comment]
![image](https://user-images.githubusercontent.com/5374350/73298671-bc3d5200-41db-11ea-9059-a9ba11f95d71.png)

You mean here?  They do provide dramatically different functions, they just happen to both open up a map view.

**Comment by SRGDamia1** [comment]
Any time you click on something "tsa" you can think "I'm moving over to a totally different website that just happens to have _most_ of the same data on it."

**Comment by dbressler75** [comment]
But what are the dramatically different functions? - once you're into TSA in Browse Sites it's the same TSA.  The main Time Series Analyst just tab on the home screen just takes you to that map with nested maroon colored sites.

**Comment by SRGDamia1** [comment]
yeah.. I guess they do kind-of feel the same.  But TSA is still basically a totally different website that just happens to share data.

**Comment by SRGDamia1** [comment]
@aufdenkampe If cost were nothing, I'd prefer to recreate it.  There are so many things about webTSA that I'd like to see changed that I hate continuing to patch it.

Prior to maternity leave, I put a lot of effort into data exploration using the [HoloViz](https://holoviz.org/) plotting packages.  Relative to the power and interactivity those provide, TSA's capabilities are pretty meager.  I have no idea how those work at the production level, but I've been impressed by what I've been able to put together.  I know @emiliom has at least heard of them, because I've seen his name in questions on their forum.

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 
We think our new TSV addresses this issue.
