### ISSUE TITLE
ODM2 / MonMW Status Dashboard

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#492]
Is there a way of being able to see the Status and activity of the system, 
I've got systems POSTing to the mmw - but none appear to being accepted.
One of the systems is a development running the latest software, so it could have a bug
Another system is a field system, with a remote context, so it could be that the weather has reduced the wireless range.
It would be nice to see some way of characterizing the operation of the system. 
Possibly hourly indications of POSTs that are received, validated, and response given - or errors.

**Comment by mbarneytu** [comment]
Agreed! Some kind of very simple MMW status dashboard would be very helpful in these cases to answer "Is it down or just me?" questions at a quick glance.
@neilh10 FWIW, I'm seeing our systems successfully logging as of 11:15am MST.

**Comment by neilh10** [comment]
@mbarneytu good to hear some logging getting through. That is the sort of feedback would be nice to see,

**Comment by aufdenkampe** [comment]
Have you all noticed this page?
https://monitormywatershed.org/status/
When logged in, it is very useful, and designed to be easily rendered on a phone from a field site when reception is low.  Does this fill your need?

Back when you posted this, we had lots of weird issues about data not showing up when it was in one of the 3 databases, due to syncing issues. This is no longer the case.

I'm going to close this issue, assuming it's been addressed, but feel free to open if not.

**Comment by SRGDamia1** [comment]
@aufdenkampe I think the functionality they were looking for here was more like https://downdetector.com/ for the status of the MonitorMW *server*, not of individual stations.

**Comment by mbarneytu** [comment]
I agree with @SRGDamia1 . It's more of a "is there a MMW-wide issue going on, or is it just my site?"; downdetector is a good example.

**Comment by SRGDamia1** [comment]
@ptomasula implemented this with #729.

The URL for the dashboard is: https://bit.ly/mmw-uptime
