### ISSUE TITLE
sensor to support battery capacity monitoring  

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#494]
Just wondering could you add a sensor to support battery capacity monitoring  - mAh or  C (Coulombs). 
This is for equipment maintenance. 

 

I would be happy with a   generic

Manufacturer:All, Model: EnergyMonitor, Variable: Charge,  Units: mAh  or C (Coulombs)

 OR could add the specific IC sensors that I'm using 
Manufacturer:ST, Model: Stc3100,
Variable: Charge Available, Units: mAh or C
Variable: Charge Used,   Units: mAh or C
Variable: Current, Units: mA or A
Variable: Voltage, Units: V
Variable: Temperature,  Units: C or F

 Stc3100 https://www.st.com/content/st_com/en/products/power-management/battery-management-ics/battery-fuel-gauge/stc3100.html

**Comment by aufdenkampe** [comment]
@neilh10, I just added:

- Equipment model: EnergyMonitor (Manufacturer = All)
- Variable: All_ExternalMonitor_BatteryCharge
  - note that this has a Variable Name = Battery Voltage, as a placeholder because there is nothing like "charge" in http://vocabulary.odm2.org/variablename/. I will be requesting that electricCharge gets added.
- Units:
  - Ampere Hour - A-hr (Electrical charge)
  - Coulomb - C (Electrical charge)
  - Milliampere Hour - mA-hr (Electrical charge)

Let me know if that works for you!

**Comment by neilh10** [comment]
Great  thanks very much. Works.
