### ISSUE TITLE
smmw: Not all data displaying 

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#517]
From https://github.com/ODM2/ODM2DataSharingPortal/issues/512
Pretty spiffing the axis assignment. 
If I look at https://staging.monitormywatershed.org/sites/TUCA-Na13/ - and download it, there is data till 2021-10-01 16:00
Looking at the Sequence number (last 4037), on the front page, the small graph shows Last Observation  Oct. 29, 2021, 7:45 p.m. (UTC-08:00)

Clicking on TSV shows new graph https://staging.monitormywatershed.org/tsv/TUCA-Na13/3959/   
and then clicking TUCA-Na13 (Equipment) EnviroDIY_Mayfly_SampleNum (Count)  
it shows some data, but only up to Mar 28, The date range is Dec-20 to Nov-21  - it doesn't show the data that exists in the date range May 27 through Oct 29er date 
However changing the date range 2021-09-01 / 2021-10-29  - it does show some data, but not all.

Do you want posts as well? ~ that represents a more realistic data flow update.
If so what would the new destination be 

I have only to change one line in an ms_cfg.ini and it will use the new address. 
[PROVIDER_MMW]
CLOUD_ID=data.enviroDIY.com

**Comment by aufdenkampe** [comment]
@neilh10, on Friday, our staging database wasn't fully synced to production for this last summer's data.

Last night, @htaolimno completed a batch synchronization and got most of that data moved over, but my understanding is that there are still some gaps. We'll likely be doing daily synchronization until we release.

So let us know if there are still data gaps.

Regarding the "Last Observation" date for each variable on each site page, it is presently set and stored in the web application's content database when a device posts data. They currently all read Oct. 29, because that's when last synced that database.  We consider this a design flaw and will eventually rewrite this code to get that date directly from the database with the monitoring data. In the meanwhile, we'll also sync the web application database.

Please do start testing our staging system by posting device data directly to  http://staging.monitormywatershed.org!
That will likely require modifying a .h files somewhere in ModularSensors. Perhaps @SRGDamia1 can quickly point us to that, and also start some of her own tests.

**Comment by neilh10** [comment]
@aufdenkampe good to see the new interface, 
however just checking what level of testing can be done - unit testing for just the graphs wingdings - or integration testing with the user visible data.
If I download the .csv file from "Download Sensors Data" on https://staging.monitormywatershed.org/sites/tu_rc_test06/
which downloads tu_rc_test06_TimeSeriesResults.csv
should I be able to see that data visualized on the new tsv? or they operating on different internal databases.

**Comment by aufdenkampe** [comment]
With the exception of the "Last Observation" date (which shows up in a few places on the web app), all data are now coming from the same database! 

So sparkline plots, CSV downloads, the table view, and TSV should all be showing the same data.

**Comment by neilh10** [comment]
yeah one source of the truth. The above display now shows me all the data.
The display date still seems to us DateTimeUTC - not the local time "DateTime". 
For me, connecting to local events,  would be SO useful to have it in the local "DateTime" and then as an option for it to select to DateTimeUTC if needed. 
We can have a lot happen in the  -8Hrs behind UTC and trying to connect it to local time events is a big deal. 
Here is the hydrograph of when the "atmospheric river" dropped on a local well studied stream. 
It had been running at 6" of water depth all year, and then climbed to the limit of the depth gauge in  about 8hours
![image](https://user-images.githubusercontent.com/2766619/141860361-442c4b53-e4f6-4edd-9cd8-c17b30cbf740.png)

**Comment by aufdenkampe** [comment]
@neilh10, thanks for that feedback!

We had intended to show you local time, AND we know there is a timezone bug somewhere in this codebase that we inherited, so it is really useful to know that this is UTC. We had some places where the UTC correction is applied twice, so we're slowly trying to piece together all time conversions.

**Comment by neilh10** [comment]
Yeah  :) timezone issues are part of our rotating planet!. I had issues with ModularSensors - my solution there was to come up with a naming convention for what is being referenced so it can be relatively easily traced.
