### ISSUE TITLE
TSV aliasing

### ISSUE THREAD

**Issue by ssueng2021** [ODM2/ODM2DataSharingPortal#536]
We had a wonderful little storm last night, and when looking at the data this morning it seems there is some visual aliasing.
For the TSV it automatically selects the date as the today date, however it seems to assume that the data be shown to today 00:00 where as I would expect it to show all the data collected today till the current time.
For https://monitormywatershed.org/sites/nh_LCC45/
the from page small tsv shows a rising hydrograph

![211212 090601 tsv short](https://user-images.githubusercontent.com/95303829/145722335-ad9d4a5d-3837-44da-ad27-d11ede4e3e53.jpg)

When invoking the larger data navigation "open in time series visualization"  it only shows the data to midnight last night, not the currently rising hydrograph

![211212 090809_to12th aliased](https://user-images.githubusercontent.com/95303829/145722414-1a09a661-9922-491b-9b0a-6ebd50d8826e.jpg)

When I change the range selector to a couple of days ahead, it  shows the last 8hrs to "now", with the rising hydrograph visible

![211212 090934to14th with last data point](https://user-images.githubusercontent.com/95303829/145722437-083491c4-d4d9-4417-ae3f-9ab7ea5bdcd7.jpg)

created by neilh10.

**Comment by neilh10** [comment]
Interesting - neilh10 posted the above. But it took the eng ID I created for some students. Possibly a bug in github.. oh lordy all this quirkiness !!!

**Comment by aufdenkampe** [comment]
@neilh10, we'll work on this soon.

**Comment by ptomasula** [comment]
@ssueng2021 @neilh10
Thanks for reporting this. We revised the java script responsible for handling those date ranges to enable it to pull any available data for the day selected as the end date. 

The previous implementation used 12am midnight as the end time, which resulted in any data for the select end not being displayed on the plot when selecting default ranges. 

One note: this is a JS related fix. Since we have not implement a fix for #529 yet, you may need to do a clear the cached JS for TSV to actually see the changed behavior. You can do this with a 'Hard Reload' on the page (CTRL + F5 for chrome).
