### ISSUE TITLE
Device POST addr

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#546]
Just want to check, from a data flow architecture do you really want the devices to POST to the same  IP#  as the front door URL resolves IP#.

Currently for a user to access a device - it is to go to the "front door" eg https://monitormywatershed.org/
or access a specific device https://monitormywatershed.org/sites/TUCA_PO03/

The devices/ModularSensors are being recommended to POST to HOST monitormywatershed.org https://github.com/ODM2/ODM2DataSharingPortal/issues/524
It used to be HOST data.enviroDIY.com, which was aliased to monitormywatershed.org 

The POST is encapsulated in an embedded device that can't easily be updated, as its encoded on the embedded device. 
There is some potential control if the  POST addr is different, though under the current ModularSensors/tinyGSM architecture it requires a software restart/(reset) to relook up the HOST to  POST IP# addr.

It would seem to me that there could be some data flow control if the user access  could be separated from the device POST, but I don't have any experience of the front end server http:// processing if it matters that much.

So just checking if the the devices to POST to the same  IP#  as the front door URL IP#.
It doesn't matter to me one way or another.

**Comment by aufdenkampe** [comment]
@neilh10, the short answer is YES, devices POST to the same URL as the web application URL that users access via a web browser.

The slightly longer answer is that all devices append `/api/data-stream` to their URL, sending their POSTs to  https://monitormywatershed.org/api/data-stream for example. This allows us to reroute device traffic to the RESTFul API endpoint, as described by #510. This is common practice for many web frameworks, including Django (which is what we've used to build Monitor My Watershed).

As @ptomasula mentioned in https://github.com/ODM2/ODM2DataSharingPortal/issues/543#issuecomment-1002275864, we have the ability to reroute device traffic anywhere we want, including to a separate AWS Instance that is functionally a separate server with it's own IP address (that is hidden to the user). We may do this in future iterations, in order to better scale.

**Comment by neilh10** [comment]
:) thanks, many thanks for the details, good for my education on the front end techniques.
