### ISSUE TITLE
Unable to submit leaf pack data, yields Server Error (500)

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#557]
@aufdenkampe Site user reported that she has tried three times since Feb. 1 to enter leaf pack data and each time she submits the web form she gets a server error (500) message. 

I just created a new test site and tried to add leaf pack data but got the same error.

Interestingly, my new site doesn't appear in My Sites or Browse Sites but is reachable at https://monitormywatershed.org/sites/WCCTEST/.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @ptomasula I notified Tara Muenz of this issue and she said she has been planning a March webinar on how to enter leaf pack data into MonitorMW. Any idea if this issue can be addressed by then or should she reschedule her webinar?

**Comment by aufdenkampe** [comment]
@HeatherBrooks, thanks for posting this issue!  

We haven't yet touched the code behind the Leaf Pack functionality since our Tech Debt work started in June. The code and database supporting Leaf Pack are all very separate from the rest fo the web application, and as such, we expected it would continue to work fine, but we clearly missed this issue!

We recognize that fixing this bug is a priority for you and the community, and we'll prioritize the fix. We'll devote some time in the next couple of days to figuring out the issue and give you an update. Hopefully it is a quick fix and Tara can keep her scheduled workshop. When exactly is it in March?

**Comment by HeatherBrooks** [comment]
@aufdenkampe I checked in with Tara: she was planning the webinar for the first week of March.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, we'll let you know by early next week if Tara might need to reschedule the webinar.

**Comment by ptomasula** [comment]
@HeatherBrooks @aufdenkampe 
I pushed a hotfix this afternoon that addresses this issue. The root cause was a missed syntax update between python 2.7 and the python 3.8. I was able to submit test Leak Pack data on our test site [https://monitormywatershed.org/sites/AnthonyTest/](https://monitormywatershed.org/sites/AnthonyTest/) 

@HeatherBrooks can you confirm that the Leaf Pack submissions are working for you as well?

**Comment by HeatherBrooks** [comment]
@ptomasula @aufdenkampe I just submitted leaf pack data on a [test site](https://monitormywatershed.org/sites/WCC%20TEST/) and everything appears to work again. Thank you! I really appreciate you pushing the hotfix. I'll let Tara know that she can go ahead with her webinar.
