### ISSUE TITLE
TSV:  Plot data is not re-ranging when date range is changed

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#583]
On staging right now, changing the date range and hitting "Update plot" or selecting last year/month and hitting update plot does not update the data displayed. The date tick mark changes, but the data itself does not.  Could this have been broken in the effort to fix #566 ?

**Comment by SRGDamia1** [comment]
This might be related to #588

**Comment by ptomasula** [comment]
Thanks @SRGDamia1, I think this is at least in part related I bug I found with our new class from managing the dynamic loading of timeseries. In commit [0c2d21b](https://github.com/ODM2/ODM2DataSharingPortal/commit/0c2d21ba7f32ac9a420736b4b005a8ef0753e89f) I fixed an issue with how that class handled null datetimes, which would prevent that class from actually loading in more data.

You're also correct that #588, is part of the problem here. If no data for the timeseries exists for the date range, then no plot line will be displayed. I think we use issue #588, as a place to resolve challenge. Some type of indication that no data is available for a given timeseries over the current date range makes a lot of sense to me.
