### ISSUE TITLE
Allow users to recover a forgotten username

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#684]
Right now users log in by username instead of by email.  There needs to be a way to recover a forgotten user name from the email or to allow either the username or the email to be valid for logging in.

**Comment by aufdenkampe** [comment]
@ptomasula, Has this been addressed already?

**Comment by aufdenkampe** [comment]
It appears that the functionality is fine. It's possible to log in with an email address if you don't know your username.

Unfortunately, the login box says username, and we can't easily change it because it is the default by Cognito.

Closing for now. If necessary, we can create a new issue, for the back burner, to implement a custom interface for Cognito.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, perhaps its worth mentioning in https://wikiwatershed.org/kbcategories/monitor-my-watershed-envirodiy-sensor-data-manual/ that a user can login with their email address as an alternate to their username.

**Comment by HeatherBrooks** [comment]
@aufdenkampe, I've updated the [Create and Edit an Account](https://wikiwatershed.org/knowledge-base/create-edit-account/) section of the Monitor My Watershed knowledge base. Please let me know if there are any additional edits. 

In particular, I'm not sure this statement is still true: "If you are independent of an organization, you do not need to include one." Is there an option to self-affiliate now?
