### ISSUE TITLE
Subscriber unable to register a new site

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#709]
@aufdenkampe @ptomasula Could this be related to last week's release? The screenshot shows an error message of "There are still some required fields that need to be filled out" but all unfilled fields are mark as optional.

[https://www.envirodiy.org/topic/registering-a-new-site-on-mmw/#post-18358](url)

**Comment by SRGDamia1** [comment]
@ptomasula I tested this. While I was logged in as my usual user with admin privileges, I was able to create a new site only filling out required fields.

I then created a completely new non-admin user to test. When I was logged in as that user, I got a 500 error just clicking on the "My Sites" page so I couldn't even test creating a new site.

**Comment by ptomasula** [comment]
@SRGDamia1, I do not receive a 500 error when as a non admin user, so that might be a separate issue we need to look into. 

I confirmed and reproduced this behavior. Likely resulting in a missing organization_id field on the form. There is supposed to be a dropdown that allows users to select with affiliated organization they want to deploy this site for, but that doesn't seem to appear for standard users. I'm look into the resolution for this now.

**Comment by SRGDamia1** [comment]
@ptomasula I created a new issue for the My Sites page. I suspect it's related by my account being brand new, not just non-administrative.

**Comment by ptomasula** [comment]
The fix for this should be live on production. Users will now see the missing dropdown that lets them select which organization to deploy the site for. 
<img width="321" alt="image" src="https://github.com/ODM2/ODM2DataSharingPortal/assets/31142705/bb99fb47-9a1e-4654-b368-435904602a71">

**Comment by HeatherBrooks** [comment]
Thank you, Paul! I will report back to the user on EnviroDIY.
