### ISSUE TITLE
TSV endpoint exposes UUIDs

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#717]
We need to think of a way to do this so the UUID's aren't exposed.

**Comment by aufdenkampe** [comment]
Thanks for bringing this up. It's important to note and consider this.

Fortunately, in ODM2, we imagined that Result UUID and Sampling Feature UUID was always intended to be public, so that databases could be easily merged and provenance would always be traceable. So it's OK that these are public.

On the other hand, we definitely want keep `registrationToken` private to the site "owner", which we do, so I think we're good.

Closing.
