### ISSUE TITLE
Add a way to view the GUID for a time series

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#92]
The GUIDs are the only things that tie the data in a post request (and the program that creates it) to any time series.  So, for debugging, it would be really helpful to view the GUID for a timeseries somewhere other than in the "code snippet."  (At least for one of my own timeseries.)  The code snippet has really helpful comments in it, but it's hard to keep straight which is which, especially when the order changes.

**Comment by SRGDamia1** [comment]
I definitely want to be able to see the GUID when in the edit site view so ~~if~~ when I realize I programmed a remote sensor to feed data to the wrong GUIDs I can fix it.

**Comment by SRGDamia1** [comment]
Just another ping to say that I think this is pretty important.

**Comment by fryarludwig** [comment]
So you specifically are asking to show the sensor GUIDs when editing your site? For example, adding a column to the sensor table?

![image](https://user-images.githubusercontent.com/8953221/34170297-95dc6c6a-e4a7-11e7-86eb-c05c7d7c106e.png)

Sensors added on the edit and create site pages aren't assigned UUIDs until the user confirms the site changes, so new sensors won't have UUIDs shown until they return to the edit page. This isn't an issue for your use case, right?

**Comment by SRGDamia1** [comment]
I want to be able to view the GUIDs when viewing the site.  So I'd like it somewhere near the respective sparkline for variables and with the other site data for the sampling feature.

For editing a site, if _editing_ and already existing variable, I want to see the GUID.

I understand that the GUID isn't assigned until after the initial creation of a site/variable.

**Comment by fryarludwig** [comment]
Thanks for that clarification, we'll bump the priority on this one.

**Comment by fryarludwig** [comment]
Referencing  #113 due to site view overlap

**Comment by jcaraballo17** [comment]
@SRGDamia1 Let us know if you have any preference or suggestions on where we should position these. I say we display the sensor UUID at the bottom of the sparkline just as it was before creating the code snippet, and also in the top part of the modal window that pops up when editing a sensor.

**Comment by SRGDamia1** [comment]
If you can make the spark line header collapsable (#113), I'd prefer it there. Also having it in the modal for editing sensors would be awesome.

**Comment by horsburgh** [comment]
@jcaraballo17 - this plan seems reasonable. Don't forget the site token and the registration token. These should only be displayed to the site owner.

**Comment by horsburgh** [comment]
@jcaraballo17 - go ahead and make it part of the header. This is a priority issue, so we should go ahead and fix it in the next round. 

@SRGDamia1 - if @jcaraballo17 puts the GUID in the header of the sparkline plots it is going to compress the size of the box containing the plot. The full element for the header and the sparkline plot uses a consistent height on the page, so if we make the header larger, the plot has to get smaller. Also, if we eventually do collapsable headers, when you expand the header it will similarly shrink the plot. 

We have to do it this way because there are two columns on the page and we need to keep the vertical spacing the same across the rows and columns.

**Comment by SRGDamia1** [comment]
Ok, understood.

**Comment by horsburgh** [comment]
@Maurier and @jcaraballo17 - this one is assigned to both of you, but I don't see any of this on the sandbox and I don't see an "In-progress" label. Which one of you is going to take care of this?

We need to get this one finished with #139. I'm not adding any labels because I don't see any evidence of this on the sandbox.

**Comment by horsburgh** [comment]
This looks good on the sandbox. However - GUIDs of all types (registration, samplingfeature, and variable) should only be visible to the site owner and admins of the system. I can see the variable GUIDs for sites when I am not logged in. @Maurier and @jcaraballo17 - which one of you should fix this?

**Comment by Maurier** [comment]
I can fix this.

**Comment by SRGDamia1** [comment]
I can see the time series GUID's now on the sandbox when viewing the sites.  I'd still like to see the GUID for an existing variable when I'm editing it.  (Of course, there is no GUID at the initial variable creation.)

![image](https://user-images.githubusercontent.com/5374350/38625820-4b39bc46-3d79-11e8-8835-2d7ecbf62b07.png)

**Comment by Maurier** [comment]
@horsburgh, 

Yes, are working on this together right now. Editing the labels has also been taken care of and will show up on the next update to the sandbox later today.

**Comment by horsburgh** [comment]
I no longer see the tokens or UUIDs when not logged on. This one looks good to go on the Sandbox. Adding the tested label.
